2016-02-17 20:19:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" already exists; SQL statement:
CREATE TABLE PERSON(id int primary key, name varchar(255)) [42101-191]
2016-02-17 20:45:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:51:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" already exists; SQL statement:
CREATE TABLE PERSON(id int primary key, name varchar(255)) [42101-191]
2016-02-17 20:51:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:51:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:51:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:51:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:54:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" already exists; SQL statement:
CREATE TABLE PERSON(id int primary key, name varchar(255)) [42101-191]
2016-02-17 20:54:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:54:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:54:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:54:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" already exists; SQL statement:
CREATE TABLE PERSON(id int primary key, name varchar(255)) [42101-191]
2016-02-17 20:55:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:55:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-191]
2016-02-17 20:59:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
select * from PERSON [42102-191]
2016-02-17 21:01:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
DROP TABLE PERSON [42102-191]
2016-02-19 20:16:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "id" not found [42122-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3155)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3217)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:339)
	at servlet.SqlServlet.doGet(SqlServlet.java:38)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2016-02-19 20:21:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
select * from PERSON [42102-191]
2016-02-19 20:22:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SQLEXCEPTION[*] "; expected "SELECT, SET, SAVEPOINT, SCRIPT, SHUTDOWN, SHOW, {"; SQL statement:
SQLException [42001-191]
2016-02-19 20:22:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
select * from PERSON [42102-191]
2016-02-19 20:24:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement """fail""[*]"; expected "FROM, {"; SQL statement:
"fail" [42001-191]
2016-02-19 20:24:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:
select * from PERSON [42102-191]
2016-02-19 21:29:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "0" for parameter "columnIndex" [90008-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:228)
	at org.h2.jdbc.JdbcResultSetMetaData.checkColumnIndex(JdbcResultSetMetaData.java:447)
	at org.h2.jdbc.JdbcResultSetMetaData.getColumnName(JdbcResultSetMetaData.java:85)
	at database.TestDBResult.test_connect(TestDBResult.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
